image: docker:19.03.8
services:
  - docker:19.03.8-dind

variables:
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE: $DOCKER_REGISTRY/tian-lp
  IMAGE_EXPORT: $DOCKER_REGISTRY/tian-lp:export

stages:
  - build
  #- deploy

build:
  stage: build
  before_script:
    - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - echo "start build"
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest -t $IMAGE .
    - docker push $IMAGE
    - docker pull $IMAGE_EXPORT || true
    - docker build --cache-from $IMAGE_EXPORT -f ./Dockerfile-export -t $IMAGE_EXPORT .
    - docker push $IMAGE_EXPORT
    - echo "done"
  only:
    - dev
  when: manual
