FROM node:14-alpine

# RUN apk add --no-cache imagemagick ffmpeg graphicsmagick \
#     && apk --no-cache --virtual build-dependencies add \
#     python \
#     make \
#     g++ 

RUN apk add --no-cache graphicsmagick \
    && apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ 

RUN apk add --no-cache shadow \
    && usermod -u 1000 node \
    && groupmod -g 1000 node \
    && mkdir -p /app \
    && chown node:node /app

WORKDIR /app

USER node

COPY ./package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN npm run buildstatic

ENV HOST 0.0.0.0
EXPOSE 3000

CMD ["npm", "run", "export"]
